language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
  - ng build --prod --base-href https://bamanczak.github.io/test-20200516/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/pesel
  on:
    branch: master
